### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by nehalist** [nehalist/Haven#1]
### General

- [x] Responsive
- [x] HTML 5 Tags
- [x] Localization
- [x] Browser testing
- [x] Post author box
- [x] Pages
  - [x] Author (`author.hbs`)
  - [x] Tag (`tag.hbs`)
  - [x] Error (`error.hbs`)
  - [x] Subscribe (`subscribe.hbs`)
  - [x] Page (`page.hbs`)
- [x] Comment placeholder
- [x] Gallery
- [x] Sharing
- [x] Readme
  - [x] Badges

### Fixes

- [x] Post details: remove opacity hover for feature image
- [x] Align content / sidebar
